In [1]:
##Write a function to compute 5/0 and use try/except to catch the exceptions

def findDiv(a, b):
    result=0
    try:
        result=int(a/b)
    except ZeroDivisionError:
        print("Number %s cannot be divisible by zero" %(a))
    else:
        print("result=",result)

In [2]:
a=int(input())
b=int(input())
findDiv(a,b)

5
0
Number 5 cannot be divisible by zero


In [3]:
a=int(input())
b=int(input())
findDiv(a,b)

10
2
result= 5


In [4]:
#Implement a Python program to generate all sentences where subject is in ["Americans",
#"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for sub in subjects:
    for verb in verbs:
        for obj in objects:
            print(sub+" "+verb+" "+obj+"\n\r")

Americans  play Baseball

Americans  play Cricket

Americans  watch Baseball

Americans  watch Cricket

Indians play Baseball

Indians play Cricket

Indians watch Baseball

Indians watch Cricket



In [5]:
##Write a function so that the columns of the output matrix are powers of the input vector

import numpy as np

def inOutPowerMatrix(inputMatrix, n, incresingOrder):
    if not incresingOrder:
        outputMatrix = np.array([x**(n-1-i) for x in inputMatrix for i in range(n)]).reshape(inputMatrix.size, n)
    else:
        outputMatrix = np.array([x**i for x in inputMatrix for i in range(n)]).reshape(inputMatrix.size, n)
    return outputMatrix

In [6]:
inputMatrix=np.array([1,2,3,4,5])

outputMatrix1 = inOutPowerMatrix(inputMatrix,5,False)
print("Increasing Order set to False")
print(outputMatrix1)
print("Increasing Order set to True")
outputMatrix2 = inOutPowerMatrix(inputMatrix,5,True)
print(outputMatrix2)

Increasing Order set to False
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
Increasing Order set to True
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
